# Generated by Django 3.0 on 2022-08-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20220821_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='uom_id',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
